export {default as Phonecall} from "./svgs/phoneCall.svg"
export {default as Lightning} from "./svgs/lightning.svg"
export {default as Key} from "./svgs/key.svg"
export {default as Check} from "./svgs/check.svg"
export {default as Icon} from "./svgs/icon.svg"
export {default as Mobile} from "./images/mobile.png"